# Generated by Django 5.1.4 on 2024-12-20 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_genres',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_genres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
