# Generated by Django 5.1.4 on 2024-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='No bio provided', max_length=255),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_genres',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, to='accounts.genre'),
        ),
    ]
