# Generated by Django 5.1.4 on 2024-12-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_genre_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='key',
            field=models.CharField(default='unknown', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
