# Generated by Django 5.1.4 on 2024-12-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_create_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='key',
            field=models.SlugField(default='unknown', max_length=100, unique=True),
        ),
    ]
